spring.application.name=centralpet

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/centralpet
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.h2.console.enabled=false
spring.jpa.open-in-view=false

# JWT
app.jwt.secret=centralpet-secret-key-do-breno-2026
app.jwt.expiration-ms=86400000

